### ISSUE TITLE
Error: 0 with Template TWO

### ISSUE THREAD

**Issue by deltapapa01** [templaza/astroid-framework#518] opened 2023-12-27 08:17 UTC
Hi @sonvnn ,

I'm playing around with my local machine right now (to lern a little bit php), I have AF 3.0.8 + Tpl installed.
I noticed that the package also contains the new TWO template, which I wanted to try out immediately.
However, I get the following error on my local XAMPP environment:

![image](https://github.com/templaza/astroid-framework/assets/19833064/01c4bab3-76cd-4938-9095-e7fd2e3ebe4a)

Template Zero and One are working fine on the machine.
b/c is off.
(I was surprised that you have already released Template Two, I didn't realize that at all :-))

WBR,
deltapapa

**Comment by sonvnn** [comment] 2023-12-27 08:57
Opp! It's problem with Xampp on Windows again. Thank you! I will find another way to require files.

**Comment by sonvnn** [comment] 2023-12-28 05:15
@deltapapa01 I fixed this issue in https://github.com/templaza/astroid-framework/commit/56dbc5ccdadb2c06ba8776cf6349c5d6ea79b9f0

Let's download v3-branch and retest on your localhost. Please update your test result here.

Thanks & Best Regards,
Sonny

**Comment by deltapapa01** [comment] 2023-12-28 06:45
Hi Sonny,

i test it with v3 branch Fw and tmpl, and it works fine now!

![image](https://github.com/templaza/astroid-framework/assets/19833064/899d1f45-0322-4b92-8f90-836794b69fd6)


Thank you :-)

**Comment by emedinainnotec** [comment] 2024-01-16 10:58
I have the same issue.
In library\astroid\Helper\Overrides.php in line 89:
return self::generateExtensionPath(\substr($callPath, stripos($callPath, '/html/') + 5));
stripos replace "c:\wa" in wamp server, and reproduce the "failed opening required file" error.
Is the '+5' really necesary?
Removing this, works fine with wamp:
return self::generateExtensionPath(\substr($callPath, stripos($callPath, '/html/')));

**Comment by Giorgi625** [comment] 2024-01-16 11:10
Wow Template Two? Its interesting, I was downloading always Framework and Template one files separately from astroidframe.work, because I do not use zero template, so I did not noticed there was Template two. 
Does it make sense to Build new websites with this template, what where can we see changelog or some sort of feature list where is shown what is difference between templates One and Two?

**Comment by sonvnn** [comment] 2024-01-16 12:04
> I have the same issue.
> 
> In library\astroid\Helper\Overrides.php in line 89:
> 
> return self::generateExtensionPath(\substr($callPath, stripos($callPath, '/html/') + 5));
> 
> stripos replace "c:\wa" in wamp server, and reproduce the "failed opening required file" error.
> 
> Is the '+5' really necesary?
> 
> Removing this, works fine with wamp:
> 
> return self::generateExtensionPath(\substr($callPath, stripos($callPath, '/html/')));

I fixed in v3-branch please download v3-branch and test it. I will soon release 3.0.9

Best Regards,
Sonny

**Comment by Chacapamac** [comment] 2024-01-16 19:58
Intereste

> Wow Template Two? Its interesting, I was downloading always Framework and Template one files separately from astroidframe.work, because I do not use zero template, so I did not noticed there was Template two. Does it make sense to Build new websites with this template, what where can we see changelog or some sort of feature list where is shown what is difference between templates One and Two?

Yeah, I’m interested to know the difference.

**Comment by sonvnn** [comment] 2024-01-17 02:16
@Giorgi625 @Chacapamac Thanks for interest! Two and One are separate templates. The Two will give your website a new style and it supports all latest features from Astroid 3 as Color Mode, Widgets, etc..

**Closed** 2024-01-18 08:59 UTC

**Comment by Chacapamac** [comment] 2024-01-19 18:53
@sonvnn — Can Wait to try 👍
You said:

> supports all latest features from Astroid 3 as Color Mode, Widgets

**One & Zero cannot work with these features?** 👀
