### ISSUE TITLE
Parallax effect / Background images not working on iPhones / iPads

### ISSUE THREAD

**Issue by badewanne1234** [templaza/astroid-framework#188] opened 2022-09-13 20:32 UTC
If one selects an image for a section (in the layout settings), its showing perfectly as a background image / parallax effect on a desktop, however the pictures are not being displayed correctly on an iPhone and/or iPad, they are super-zoomed in, which is pretty weird. No matter if Safare or Firefox is being used. The image applied has a size of 2050x1000 pixels.

Settings applied for the image are (I have tried all of them, nothing worked) are:

Design Settings
- Background repeat: no repeat
- Select a background size: cover
- Select a background attachment: fixed
- Select a background position: center center

Thank you for looking into this

**Comment by Chacapamac** [comment] 2022-09-19 13:08
I @badewanne1234, 

I test with a same size than you image —> 2050x1000 pixels

I don't know what you want to achieve with —> **background attachment: fixed** ?

**But this is how it look like on my test website** —> http://joom4-astro.graf-test.ca/

**ON DESKTOP**
![back-fixed-desktop](https://user-images.githubusercontent.com/1907276/191023745-fc67ea76-b6f2-4622-b87d-6536434a6588.jpg)

**ON PHONE**
![fixed](https://user-images.githubusercontent.com/1907276/191023964-e09441b6-6ca3-4871-bb40-e1779b0e4ff2.jpg)

———————————————————————————————

• **Not to pretty to my taste — The following is with** —> **background attachment: Inherit**
![back-inherit-desktop](https://user-images.githubusercontent.com/1907276/191024479-467ed9a1-db39-4b1d-95d1-5babd366ec99.jpg)

![back-inherit-Phone](https://user-images.githubusercontent.com/1907276/191024506-a79a1486-ed85-41c6-82e0-2b248675db2d.jpg)

**Comment by badewanne1234** [comment] 2022-09-20 10:40
When you have longer text (not only a title), one would have the parallex effect. meaning, the background image stays where it is and the text scrolls over it - very nice effect.
The problem here is, that as soon as you select "fixed", the size of the image changes on iPhones/iPads.

Yes I could select scroll/inherit, the size is then correct on iPhones/iPads, but then the parallax effect is gond.

So the improvement would be to have the same size of the image on an iPhone/iPad when you select fixed background, compared to the image size when selecting scroll/inherit.

You can see an example of the parallax effect here: https://demo.joomlaplates.de/time in the section "We love Joomla
and we love Designs", with the black clock in the background.

**Comment by Chacapamac** [comment] 2022-09-21 12:57
I understand what you mean now. It seem that the “Fixed” position when use with background-size “Cover” do that.

**I quote somebody talking about that same problem.**

> background-attachment: fixed will handle the image as if the element was 100% height and width of the viewport. Therefore background-size: cover; will resize the image height to fit the viewport.

For sure, using “Contain” and “Fixed” give the parallax effect and keep the image width contain to 100% of the Viewport.

**Beautiful Template @badewanne1234**

**Comment by badewanne1234** [comment] 2022-09-21 17:45
I tried background-size “Contain” and background-attachment “Fixed” as well, but that does work only on desktop, on iPhones there is no parallax with this setting (same goes for background-size “Inherit” and background-attachment “Fixed”). 
Apart of the picture being zoomed in on the iPhone when you select background-size “Cover” and background-attachment “Fixed”, there is no parallax effect at all.

There seems to be an issue with the parallax in general on iOS devices, I think it has to do with how "fixed" is handled.

Parallax in general works on iOS devices, you can test it for example here: https://orangeable.com/tools/css-parallax-scroll/

**Comment by Joomlaplates** [comment] 2022-09-22 15:08
Parallax effect is not working on any Browser. And its not an issue.
Setup your image property from fixed to >> scroll and its working.
And finally you can copy this section and use one section with background for mobile and one for desktop.
![fixed](https://user-images.githubusercontent.com/71080509/191783990-2a4923d8-cace-47f0-9004-ffb7219e30e4.jpg)

**Comment by badewanne1234** [comment] 2022-09-22 19:38
If you set that to scroll, the image scrolls with the text and the parallax effect dissapears also on the desktop.
Firefox on iOS supports parallax as you can see on this link: https://orangeable.com/tools/css-parallax-scroll/

There is an issue with the parallax implementation for iOS / iPad on the Astroid Framework as far as I can tell from my tests.

**Comment by Chacapamac** [comment] 2022-09-23 16:07
Yes, with the actual settings possible in Astroid it's hard to create an easy parallax effect that fix the problems when view on different devices. 
Maybe adding an easy “Parallax Background” Choice with the right styling to make a foolproof **Parallax Background Image** ????

I mark it as an enhancement

I think the problem is that the “fixed” background need to be center on the height of the container section, not the viewport.

**Comment by badewanne1234** [comment] 2022-09-28 19:39
Thanks, looking forward to see whether it is possible :)

**Comment by Joomlaplates** [comment] 2022-12-17 09:08
Hello together,
the problem is the IOS System. They do not support the css parameter > cover fixed.
The css cover and scroll is working.
https://developer.apple.com/forums/thread/99883
https://stackoverflow.com/questions/24154666/background-size-cover-not-working-on-ios
..
I close it now, coz it has nothing todo with Astroid

**Closed by Joomlaplates** 2022-12-17 09:08 UTC
Labels: enhancement
