### ISSUE TITLE
Sticky Header not working with new Article Module in J5.2

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#849] opened 2024-10-29 13:10 UTC
- J 5.2
- Astroid 3.1.6
- Template TWO
- 
The sticky header is not working anymore when the new Article Module switched from vertical to horizontal view.
![article](https://github.com/user-attachments/assets/f871df2e-fd4b-42cc-979c-a95c4a3e622e)
I can give you acccess to the dev site if you want.
Regards Peter

**Comment by WM-Loose** [comment] 2024-10-29 14:37
Hi Sonny, hi Peter,
the cause lies with Joomla and will be fixed.
Here are all the details and the solution:

https://github.com/joomla/joomla-cms/issues/44369

Have a nice day

**Comment by sonvnn** [comment] 2024-10-30 01:36
@WM-Loose Thanks for the update. We need to wait for Joomla to update the fix version.

**Closed** 2024-11-23 01:48 UTC
Labels: Not Astroid related
