### ISSUE TITLE
long loading and problems with saving in templates

### ISSUE THREAD

**Issue by SerGun78** [templaza/astroid-framework#79] opened 2022-01-18 17:41 UTC
Backend Astroid animation is terribly slow. It needs to be removed altogether. Plus, there are constant problems with saving templates ONE and ZERO in styles. Even without changing anything, the Save button is on. When saving, problems periodically arise, either nothing is recorded, or it is recorded with errors, the external interface starts to float, content, menus, etc. disappear.

**Comment by Chacapamac** [comment] 2022-01-18 18:58
> Backend Astroid animation is terribly slow. It needs to be removed altogether.

Yep, kind of slow!, I agree...

**• You can disable the Astroid animation in the Astroid plugin**

![loader](https://user-images.githubusercontent.com/1907276/149995972-48fecb46-da95-4842-9b0d-445a0b006edf.jpg)

**Even if you disable it, the Backend Astroid, to my experience will still stay slow to load completely**.
It is far to be instantaneous. 

**Behaviour:**
When  the animation is disable and enter the layout you will see the save button flash _**(for almost 30 seconds)**_ & stop.

 **I believe that the administration is not ready to be use until it finish flashing.** 
Maybe this the cause of your errors (I never experience these type of errors in using Astroid for 3 years...) I think that clicking away, as I was doing before when entering the layouts admin, I was trying to click the Save button as it supposed to tell you that something need to be save but, in fact, when you enter it tell you the administration ready state...

Trying to reduce the time of loading here is surely something that should be look at, 30 sec is really to long.
The flashing button on arrival can be disconcerting. 
Personally as a UI designer I will cover the flashing button with a dim un-flashing/inert button. Like that no possibility to save before the admin is fully load. It will stop people to click everywhere, not knowing what’s happening.

**You can see the time here** (it will loop at the end)
![loading-gif](https://user-images.githubusercontent.com/1907276/150001271-0a853606-3723-4f01-870f-d7e0bd9220b1.gif)

**Comment by SerGun78** [comment] 2022-01-18 20:01
I have this green circle sometimes constantly blinking. save or don't save, wait or don't wait. The behavior is completely unpredictable.

**Comment by Chacapamac** [comment] 2022-01-18 22:42
> I have this green circle sometimes constantly blinking. save or don't save, wait or don't wait. The behavior is completely unpredictable.

That is weird, I never see that in 3 years using astroid and template zero. 
• What is your setup.
Joomla version/ php / Astroid version / Template 

• **Did you try in another layout or even in a copy of the layout you working on?**
— I will try an untouched layout that come with the template _( e.g. astroid_template_one - Default )_

**One thing that I remark**
If I go in an untouched layout  _(I always work on copy of the original templates to keep a clean version)_ _(I try astroid_template_one - Default & Zero )_, **the first time I go in them the green dot keep flashing _(saying save)_ forever**? 1. If I save the layout as is, it stop right away 
2. It start to flash again when I make the least change.
3. If I save my change it stop right away
4. If I close the layout and open it again, I got the 30 seconds flash and a stop
5. It start to flash again when I make the least change

**With the problems you’re having:**
_When saving, problems periodically arise, either nothing is recorded, or it is recorded with errors, the external interface starts to float, content, menus, etc. disappear._

I think something is wrong/corrupt in the Astroid installation or the layout:
(Can also be the environment, hard to pinpoint without testing...

**— If possible create a copy/backup of your website**
Ideally working on a copy:
— Try an untouched template layout or in a copy of the one you have problem with
— try to create the problem to see if anything is picked-up in a browser console or on the server logs

Maybe something went wrong at the installation, something is missing? (it happen with any software) 
— Try reinstalling Astroid over (just Joomla install the exact same package you already have (I will re-download the installation fil, just to be sure)

**Comment by Joomlaplates** [comment] 2022-01-19 10:00
Hi together,
finally he is right. And if you disbale the Astroid loader it could happens, that all font settings are gone if you start to early to edit something.
Anyway, the Astroid backend loading is horrible long and annyoing. Comparing to Helix, which is similar the Astroid is an old car!
Maybe Sonny have an idea to make it faster!

**Comment by Chacapamac** [comment] 2022-01-19 17:36
I try Helix, good but not as flexible and easy to use. It’s simple, you cannot do whatever you want without going deep in the system. In Astroid, they seem to think at that and deliver an extremely flexible tools.

================
 **Anyway, this Layout Manager behaviour is a MAJOR problem that need to be fix...**
================

**I retest again** and @SerGun78  is right it is no constance in the behaviour and the length to get in a ready state (if it get there) is a big problem.

================
**One thing is sure:**
================
**The blinking “Save” button state is definitively some kind of unsaved state**
— If you try to use the “close” button when blinking, you get the “Do you want to leave this page” warning. Meaning that any changes will be lost (I presume)

If you button “Save” the layout, the “Template Save” right bottom message appear and the blinking stop.
(sometime the blinking state stay after saving, you have to save again?????)

— If you use the “close” button, then, no warning and the layout page close.


================
**Behavior of my untouched “astroid_template_one - Default”**
================
- When enter the first time blink forever
- When “Save” / “Close” properly and reopen
- Blinking for 20 seconds and stop — ready to work

**NOT CONSTANT:**
- The behaviour seem to change from time to time - Not constant - Sometimes going back to the forever state ????

72 requests
5.45 MB / 1.38 MB transferred
Finish: 27.57 s
DOMContentLoaded: 1.86 s
load: 1.92 s

**Obvious Errors / Warnings**
11:18:26.728 unreachable code after return statement
_Learn More on that error:_
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Stmt_after_return

11:18:27.612 downloadable font: OS/2: Bad sTypoLineGap, setting it to 0: -32 (font-family: "Dropdown" style:normal weight:400 stretch:100 src index:0) source: data:application/x-font-ttf;charset=utf-8;base64,AAEAAAALAIAAAwAwT1MvMggjB5AAAAC8AAAAYGNtYXAPfuIIAAABHAAAAExnYXNwAAAAEAAAAWgAAAA … AG0AbwBvAG4ARgBvAG4AdAAgAGcAZQBuAGUAcgBhAHQAZQBkACAAYgB5ACAASQBjAG8ATQBvAG8AbgAuAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=

**Behavior of my untouched “astroid_template_zero - Default”**

- When enter the first time blink forever
- When “Save” / “Close” properly and reopen
- Blinking for 6 seconds, stop and Blink again forever ?????
- When “Save” blinking stop
- Close & reopen restart the same dance: blinking - stop few second and blink forever

**NOT CONSTANT:**
- The behaviour seem to change from time to time - Not constant - Sometimes going back to the forever state ????

68 requests
5.60 MB / 1.51 MB transferred
Finish: 5.97 s
DOMContentLoaded: 1.85 s
load: 1.90 s

**Obvious Errors / Warnings**
11:28:34.527 unreachable code after return statement

11:28:35.372 downloadable font: OS/2: Bad sTypoLineGap, setting it to 0: -32 (font-family: "Dropdown" style:normal weight:400 stretch:100 src index:0) source: data:application/x-font-ttf;charset=utf-8;base64,AAEAAAALAIAAAwAwT1MvMggjB5AAAAC8AAAAYGNtYXAPfuIIAAABHAAAAExnYXNwAAAAEAAAAWgAAAA … AG0AbwBvAG4ARgBvAG4AdAAgAGcAZQBuAGUAcgBhAHQAZQBkACAAYgB5ACAASQBjAG8ATQBvAG8AbgAuAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=

**First going in I get a 403 on all the logos and favicon, not sure why ?**
11:28:36.618
GEThttp://new-astroid.graf-test.ca/images/astroid_template_zero/favicon.png[HTTP/1.1 403 Forbidden 16ms] 
11:28:36.634
GEThttp://new-astroid.graf-test.ca/images/astroid_template_zero/logo.png[HTTP/1.1 403 Forbidden 15ms] 
11:28:36.639
GEThttp://new-astroid.graf-test.ca/images/astroid_template_zero/logo_mobile.png[HTTP/1.1 403 Forbidden 15ms] 
11:28:36.643
GEThttp://new-astroid.graf-test.ca/images/astroid_template_zero/logo_sticky.png[HTTP/1.1 403 Forbidden 15ms]

**All of them appear as broken images**
**_For Sure, clearing the image in the layout admin fix that._**

===============================================
**Now if you look at that console log text (zip file) (from Template Zero)**
===============================================
You will see a lots of errors and warning that probably have to be check.....

[console-export-2022-1-19_12-18-28.txt.zip](https://github.com/templaza/astroid-framework/files/7899264/console-export-2022-1-19_12-18-28.txt.zip)

**Comment by djayko** [comment] 2022-01-19 17:51
@Chacapamac just a big Thank you for your extensive support!

**Comment by Chacapamac** [comment] 2022-01-19 17:57
Thanks @djayko , No problem, I try to help to the best of my ability. Sadly I’m not a great coder (php,Javascipt...)
**Good Day to ALL!**

**Comment by sonvnn** [comment] 2022-01-20 02:17
Hi All,

Thank you for feedback. Yes, I agreed that loading performance is a major problem. I feedback to Joomdev since v2.5.2. But nothing improved. I will spend time to improve this in v2.5.13.

Best Regards,
Sonny

**Comment by SerGun78** [comment] 2022-01-20 09:48
Sonny, if this global problem is not resolved, it will alienate users from the asroid framework.

**Comment by djayko** [comment] 2022-01-20 10:22
@Chacapamac @sonvnn 

More information for Error "unreachable code after return statement"
caused by file: 
[https://github.com/templaza/astroid-framework/blob/master/assets/vendor/angular/ezlb.js](https://github.com/templaza/astroid-framework/blob/master/assets/vendor/angular/ezlb.js)

on line 46:
I don't understand why there is some code after the return function which is the end of this function. (but same on my site, I'm not an developer, but having some beginner experiences with scripting).


```
function generateID() {
    return Math.random().toString(36).substr(2, 9);
    var r = Math.random() >= .5;
    if (r) {
        var x = Math.floor(Math.random() * 10 + 1);
        var y = Math.floor(Math.random() * 100 + 1);
        var z = Math.floor(Math.random() * 10 + 1)
    } else {
        var x = Math.floor(Math.random() * 10 + 1);
        var y = Math.floor(Math.random() * 10 + 1);
        var z = Math.floor(Math.random() * 100 + 1)
    }
    var t = Date.now();
    return x + y + z + t.toString()
}
```

**Comment by Chacapamac** [comment] 2022-01-20 15:05
Just a addition
This is the **TimeToFirstInteractive** (TTFI) = **46.6 seconds**
And I did have to Save to stop the timer
I will also search on my side what cause this extremely long rendering...

![TTFI](https://user-images.githubusercontent.com/1907276/150364655-45ab1e81-a42b-4ff5-b737-c22defee6d17.jpg)

Kind of important, as it is the main tools to control Astroid...

**Comment by djayko** [comment] 2022-01-20 16:06
> Just a addition This is the **TimeToFirstInteractive** (TTFI) = **46.6 seconds** And I did have to **Save** to stop the timer _I will also search on my side what cause this extremely long rendering..._
> 
> ![TTFI](https://user-images.githubusercontent.com/1907276/150364655-45ab1e81-a42b-4ff5-b737-c22defee6d17.jpg)
> 
> Kind of important, as it is the main tools to control Astroid...

Hey @Chacapamac ,
Could you please provide details about your browser setup? plain browser without add-ons or extensions.

I used chrome(Version 97.0.4692.71 (Offizieller Build) (64-Bit)) with ghostery and ublock origin and got a loading time of approx. 12 seconds every time.
I did 5 tests.

**Comment by Chacapamac** [comment] 2022-01-20 19:08
**Be sure to wait until the green dot stop flashing on the button “Save”** because until this happen the **TimeToFirstInteractive** is not over and the page is not ready to interact with.
 
**When my button stop flashing the Finish time jump from:**

![Screen Shot 2022-01-20 at 1 56 09 PM](https://user-images.githubusercontent.com/1907276/150404424-1e1b03d8-bd34-4dab-aabc-b5d84bd081ab.jpg)
to
![Loading Time](https://user-images.githubusercontent.com/1907276/150403284-7417ee74-55c1-4942-be54-62e9696c046c.jpg)

Also the 70 request become 72 request (not shown on the second image)

———————————————————————————————

If your “Save” button is flashing and you wait 5 minutes and press “Save” your time to completion jump to 5 minutes +
Something is hanging the Layout manager in a “Unsaved” state when you first open a layout and hang there for around 30 seconds in that unsaved state — Sometime it just hang there indefinitely until you press “Save”

———————————————————————————————

I made that waterfall and indicate all the non-stop long process — Remark that I press the “Save” button (it was in that hang state)
_Maybe that can help?_
![waterfall](https://user-images.githubusercontent.com/1907276/150405544-1d018800-d16c-416b-8f59-c39eed026001.gif)
?

**Comment by djayko** [comment] 2022-01-21 10:34
that's a strange behaviour.
I tested it now at firefox and got TTFI of approx. 20seconds.

Setup:
- loading animation on (this asteroid thingy)
- wait till green dot flashing ends (btw. it always ends if loaging animation ends on my site)
- fully loaded: 72 requests counted

best, 
Ayko

**Comment by djayko** [comment] 2022-01-21 11:02
> **Be sure to wait until the green dot stop flashing on the button “Save”** because until this happen the **TimeToFirstInteractive** is not over and the page is not ready to interact with.

**Yes, I'm sure ;-) ** I always waited till animation end and also green dot flashing.

I can't reproduce this long loading time.

**Comment by Chacapamac** [comment] 2022-01-21 16:11
To reproduce very long time you need to have the **Flashing dot forever problem**.
In my last example, I did have to click the save button to stop the hanging process and have my TTFI
(You can see in the waterfall ”**Dom Event**” my click save action.

In precedent tests when I enter the layout and the blinking stop by itself the TTFI play between 20 to 40 seconds

**Comment by Chacapamac** [comment] 2022-01-25 13:58
Personally, if that system of “Look for change” & “Start Flashing warning when changed” is to difficult to fix now. I will get rid of the feature altogether. If I look at the loading numbers, without it, the Astroid backend should be more than snappy.

**Comment by Joomlaplates** [comment] 2022-02-04 15:17
Just my opinion:
I would remove the **Backend loading** switch from Astroid options and always show an animation to load the backend in percent.
Because some users disable the backend loader and  then they start to edit even the files are not loaded already.
Regards Peter

**Comment by sonvnn** [comment] 2022-03-14 04:15
Hi @mohdyasseribz & @siewho,

May you give us some advise about this issue? You have back-end experience in EasyBlog, EasySocial. Your experience is very helpful in this case.

Kind Regards,
Sonny

**Comment by Chacapamac** [comment] 2022-04-17 15:46
@sonvnn , 
**did you try to just take out the script that wait for inputs changes to bring the blinking light?**

**It will give you the indication if it is the problem ?**
I personally think it is.....

**If it is**, You can take this feature out until we find something better. 
—> **Anybody knows that if you are changing something, you need to save your changes.**

—> You can replace it for a simple warning if people want to close the windows without saving, for now....

**Comment by sonvnn** [comment] 2022-04-18 07:30
Hi @Chacapamac 

Thank you I will check it and response you soon.

Best Regards,
Sonny

**Comment by Chacapamac** [comment] 2022-04-19 11:26
I will try on my side, just need some time....

**Comment by Chacapamac** [comment] 2022-05-29 20:00
The Astroid animation is a good way to not have problems when playing in the Layout Manager. Also people need to check that they don’t have a blinking light when doing export/Import opération – Anyway, I did love my Astroid animation. It just tell Us to Chill out a bit.

**Closed** 2023-12-14 09:21 UTC
Labels: bug
