### ISSUE TITLE
Combo box - content can no longer be deleted

### ISSUE THREAD

**Issue by deltapapa01** [templaza/astroid-framework#285] opened 2023-01-30 18:54 UTC
Hello,
I noticed a small detail:
If I edit the properties of a column under layout, and there on the Responsive Settings, I can enter values for Extra large order or Large Order, for example.
When I open the settings, there is no value in the combo boxes:
![image](https://user-images.githubusercontent.com/19833064/215567806-2c3de639-9a8f-4d6d-a1bd-5125b3229af2.png)

If I now select a value here (1,2 or 3 for example), save and then want to delete this value again, that there is nothing more inside as at the beginning, this does not work. The value "Standard" always remains inside:
![image](https://user-images.githubusercontent.com/19833064/215568457-9522c32e-1896-48c4-a3fb-e22b45dc6937.png)

So I have no possibility to delete the field again, which is a bit confusing.
![image](https://user-images.githubusercontent.com/19833064/215568924-710e9520-a67f-47f6-81cf-034520d1b28d.png)

With best regards
deltapapa

**Comment by Chacapamac** [comment] 2023-02-02 14:25
Hello @deltapapa01 

On Joomla 4.2.6 / 4.2.7
Last Astroid

**I just check and I was able to save the “Order”.**

![Screen Shot 2023-02-02 at 9 02 32 AM](https://user-images.githubusercontent.com/1907276/216347909-7b2a371a-7445-4bf1-9368-8454cea33891.jpg)

Be sure that before trying to change any settings in the Template Manager that Astroid is not on a “Saving State” (with the blinking light)
![Screen Shot 2023-02-02 at 9 07 57 AM](https://user-images.githubusercontent.com/1907276/216349801-aeee4c75-0392-44eb-8054-07b9fde1c4ac.jpg)

In my experience, it seem to happen from time to time that the Template Manager open in a “Saving State” even if the Astroid animation is over. When it happen I always press the button “Save” and start editing the Template Manager settings only when the system is in a “Ready” state (without the blinking light)
![Screen Shot 2023-02-02 at 9 25 35 AM](https://user-images.githubusercontent.com/1907276/216351144-35c7a96d-50a7-424c-a4ee-5d569e9c5fb1.jpg)

**Comment by deltapapa01** [comment] 2023-02-02 16:28
Hi,
thanks for your answer.
With the saving thing, i have no probs.
But: "The only “not to weird” thing after coming back to “Default” I get “Default” in the settings compare to “Empty”" is exactly what I mean. Once something is entered in the box and saved, the box is no longer empty, but then there is always "Default" inside, which is a bit confusing, because I do not know what "Default" is.
Maybe the "Default" values should always be entered directly when installing the template, then this is much more obvious.

WBR,
deltapapa

**Comment by Chacapamac** [comment] 2023-02-03 00:07
Hi, @deltapapa01 
**Ok, I see, I was thinking that your settings didn’t save. Good.**
I will mark the issue as an enhancement, because it’s probably not a bug. 
**I agree it’s a bit confusing....** — Choosing ”**Default**” should present an empty choice to be uniform with the others originals fields, or maybe put “**Default**” on all fields if not modified.

**@sonvnn — An enhancement of the interface.....**

**Good Day to All!**

**Comment by sonvnn** [comment] 2023-02-03 00:45
@deltapapa01 @Chacapamac Thank you for your suggestion. I will update this issue in the next version.

Good Day to All!

**Comment by Chacapamac** [comment] 2023-02-03 16:35
@deltapapa01  
**Can we close the issue?**

**Good Day!**

**Comment by deltapapa01** [comment] 2023-02-05 09:17
Hello,
Yes, I would be happy to.
One more hint: Maybe it wouldn't be bad if the DEFAULT values were displayed somewhere, so that you know which values are where.

WBR,
deltapapa

**Comment by sonvnn** [comment] 2023-02-07 04:33
@deltapapa01 
Thank you for your feedback. I will improve this in the next version. 

Best Regards
Sonny

**Closed** 2023-02-23 03:23 UTC
Labels: enhancement, SOLVED!
