### ISSUE TITLE
Position or override

### ISSUE THREAD

**Issue by rinka88** [templaza/astroid-framework#181] opened 2022-08-29 17:52 UTC
Hello Is it possible to ask to add the name of a few more positions in the templatedetails. ( like the old fashioned way🙂 ) So that it was possible to add when creating new modules. And now you add it, but when you update it is erased. or the possibility of a child template

**Comment by Chacapamac** [comment] 2022-08-30 02:02
Just Test Update Astroid framework 2.5.19 to last 2.5.20 with a new position/module made by adding a custom position first in a custom Module and load in Astroid Layout Manager with Template One, last Joomla 4.

Everything is fine after update???
The same custom position created in 2.5.19 is still in my Astroid Layout manager and the module that was assign to it is still showing up in frontend after update.

Can you give more details on the Joomla/Astroidversions/php you are using, I cannot reproduce?

**Comment by rinka88** [comment] 2022-08-30 07:48
I meant the templateDetails.xml file. Everything that is changed there is erased after the next update. It’s better to add more position there or the ability to make a child template

**Comment by Chacapamac** [comment] 2022-08-30 13:46
**I see now @rinka88 , yes, I think that the solution here is to follow the great core Joomla and use the new child template solution.**

I follow, somewhere, a discussion with @sonvnn about the Joomla 4 child template possibility and, if my memory is right  Sonny said that Astroid will follow and include the child template possibility. 

After, looking around, I see that it seem that some of the big frameworks will implement the possibility to be true and fully use the power of Joomla. But, It also seem that a good rewrite work is needed for it and it it will take some time to become mainstream. 

Other frameworks seem to, for now, disregard Joomla core and continue to bypass Joomla and force users to go THEIR Own ways.

**I mark this as an enhancement.**

**Comment by sonvnn** [comment] 2022-09-20 09:45
@rinka88 @Chacapamac Hi, I am working with Astroid version 2.6.0. In this version will support child-template. You can check it here https://github.com/templaza/astroid-framework/pull/189/files

- You can download developer version for testing https://github.com/templaza/astroid-framework/tree/developer
- Download One Template here https://github.com/templaza/astroid-framework/tree/one-template

Please help me check it and give me your feedback.
Thanks & Best Regards,
Sonny

**Comment by sonvnn** [comment] 2022-09-20 11:38
@rinka88 One more issue I'm working with is the ability to copy configure from parent template to child when create child template. I will complete it, tomorrow. Please wait for testing it.

Thank you very much!
Best Regards,
Sonny

**Closed** 2022-10-06 09:08 UTC
Labels: enhancement
